baseURL: https://hbs-skeleton.netlify.app/
title: Erovast
copyright: "Copyright © 2016-{year} Trevor Nally"
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: false
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: false

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  # news: /news/:year/:month/:title/
  # blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/the5isoutloud/erovast-codex-deploy/site
#   proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
